### ISSUE TITLE
PT course invitation text not rendering apostrophe in instructor's name

### ISSUE THREAD

**Issue by gmerritt** [PrairieLearn/PrairieTest-feedback#75] opened 2024-10-30 17:12 UTC
For a Course Owner with an apostrophe in their name, the PT Course Invitation for Students is rendering the html escape sequence for an apostrophe, not the apostrophe:

> This course is owned by Grace D O&#39;Connell

The Owner's name renders nicely in the Course Staff roster:

> Grace D O'Connell

Can PT be made to render the apostrophe in the Course Invitation context?

Thanks!

**Comment by nwalters512** [comment] 2024-10-30 18:02
I believe I understand what the issue is, but can you include a screenshot? I fear that GitHub is rendering the escape sequence you typed out as an apostrophe 😂

**Comment by gmerritt** [comment] 2024-10-30 18:05
![Image](https://github.com/user-attachments/assets/b154c05b-ca31-4487-924b-7579b66771ab)

**Comment by nwalters512** [comment] 2024-10-30 21:03
This will be fixed by https://github.com/PrairieLearnInc/PrairieTest/pull/2072 (private repository).

**Closed as completed** 2024-10-30 22:41 UTC
