### ISSUE TITLE
Cheatsheet homework not accessible in CBTF

### ISSUE THREAD

**Issue by ZacWarham** [PrairieLearn/PrairieTest-feedback#72] opened 2024-09-25 23:32 UTC
We have been using a homework assessment that allows students to upload a cheatsheet that can be viewed during their quizzes in the CBTF

![image](https://github.com/user-attachments/assets/fa18a2fb-7e0d-46b2-a59b-f390acb82c89)

However if the student clicks on this link it says it is closed

![image](https://github.com/user-attachments/assets/a3dc9227-ed5e-435c-8302-d7c61f4da464)

To open the cheatsheet you have to click on assessments at the top to be taken to this page

![image](https://github.com/user-attachments/assets/9cf0af3c-9fce-4a6f-8b0c-b6668189ce19)

Then access from here.

This appears to be a result of setting `active: false` inside of our `assessment.json` during the time that the quiz is open

```
"allowAccess": [
        {
        "startDate": "2024-09-24T11:00:00",
        "endDate": "2024-09-24T13:00:00",
        "credit": 100
      },
       {
        "startDate": "2024-09-24T13:00:00",
        "endDate": "2024-09-24T14:00:00",
        "active": false,
        "showClosedAssessment": true
      },
      {
        "mode": "Exam",
        "examUuid": "session_was_here",
        "showClosedAssessment": true,
        "active": false
      }
```

Our setup is this way so the students can
1. Upload a cheatsheet prior to the quiz day
2. Double check it exists but not submit anything further during the quiz window
3. View the quiz in the CBTF with the examUUID

From our understanding, switching the second access role to be `active: true` fixes the issue but would allow resubmissions. Is this a misunderstanding of access roles which is causing the need for a workaround to access the cheatsheets or is it a bug in the system?

**Comment by nwalters512** [comment] 2024-09-25 23:35
Is this a duplicate of #71?

**Comment by ZacWarham** [comment] 2024-09-25 23:38
> Is this a duplicate of #71?

I skimmed it earlier and thought it was a different situation but looking further it is likely the same problem just repeated in a different way sorry. Should I move my post as a comment there?

**Comment by nwalters512** [comment] 2024-09-25 23:40
If you think you can add any new information, yes, please comment on that issue. I'll close this as a duplicate.

**Closed as not planned by nwalters512** 2024-09-25 23:40 UTC
